FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY src/ ./src/

# Persist DB in a volume
VOLUME ["/app/data"]

ENV PORT=3001

EXPOSE 3001

CMD ["node", "src/index.js"]
